# Generated by Django 5.2.5 on 2025-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
